Talento/Controllers/CandidatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Talento.Data;
using Talento.Models;

namespace Talento.Controllers
{
    public class CandidatoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CandidatoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Candidato
        public async Task<IActionResult> Index()
        {
            return View(await _context.CandidatoViewModel.ToListAsync());
        }

        // GET: Candidato/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatoViewModel = await _context.CandidatoViewModel
                .FirstOrDefaultAsync(m => m.IdCandidato == id);
            if (candidatoViewModel == null)
            {
                return NotFound();
            }

            return View(candidatoViewModel);
        }

        // GET: Candidato/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Candidato/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCandidato,Apaterno,Amaterno,Nombre,Edad,FechaDeNacimineto,Pais,Estado,Ciudad,CodigoPostal,Correo,Telefono,Celular,Escolaridad,UltimoPuesto,SueldoDeseado,Comentarios,AvisoPrivacidad,FechaRegistro")] CandidatoViewModel candidatoViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(candidatoViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(candidatoViewModel);
        }

        // GET: Candidato/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatoViewModel = await _context.CandidatoViewModel.FindAsync(id);
            if (candidatoViewModel == null)
            {
                return NotFound();
            }
            return View(candidatoViewModel);
        }

        // POST: Candidato/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCandidato,Apaterno,Amaterno,Nombre,Edad,FechaDeNacimineto,Pais,Estado,Ciudad,CodigoPostal,Correo,Telefono,Celular,Escolaridad,UltimoPuesto,SueldoDeseado,Comentarios,AvisoPrivacidad,FechaRegistro")] CandidatoViewModel candidatoViewModel)
        {
            if (id != candidatoViewModel.IdCandidato)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidatoViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidatoViewModelExists(candidatoViewModel.IdCandidato))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(candidatoViewModel);
        }

        // GET: Candidato/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidatoViewModel = await _context.CandidatoViewModel
                .FirstOrDefaultAsync(m => m.IdCandidato == id);
            if (candidatoViewModel == null)
            {
                return NotFound();
            }

            return View(candidatoViewModel);
        }

        // POST: Candidato/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidatoViewModel = await _context.CandidatoViewModel.FindAsync(id);
            _context.CandidatoViewModel.Remove(candidatoViewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidatoViewModelExists(int id)
        {
            return _context.CandidatoViewModel.Any(e => e.IdCandidato == id);
        }
    }
}

Talento/Controllers/TalentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Talento.Data;
using Talento.Models;

namespace Talento.Controllers
{
    [Route("Home")]
    public class TalentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TalentController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("{view=Index}")]
        public IActionResult Index(string view)
        {
            ViewData["Title"] = "Páginas de Talent";
            return View(view);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Usuario,Membresia,Apaterno,Amaterno,Nombre,Empresa,GiroEmpresa,Puesto,Telefono,Correo,Ciudad,TipoMembresia,FechaIngreso")] Users users)
        {
            if (id != users.Id_Usuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.Id_Usuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Perfil" , "Home");
            }
            return RedirectToAction("Index", "Home");
        }
        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.Id_Usuario == id);
        }

    }
}

Talento/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Talento.Data;
using Talento.Models;

namespace Talento.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Id_Usuario == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Perfil([Bind("Id_Usuario,Membresia,Apaterno,Amaterno,Nombre,Empresa,GiroEmpresa,Puesto,Telefono,Correo,Ciudad,TipoMembresia,FechaIngreso")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Usuario,Membresia,Apaterno,Amaterno,Nombre,Empresa,GiroEmpresa,Puesto,Telefono,Correo,Ciudad,TipoMembresia,FechaIngreso")] Users users)
        {
            if (id != users.Id_Usuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.Id_Usuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Id_Usuario == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var users = await _context.Users.FindAsync(id);
            _context.Users.Remove(users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.Id_Usuario == id);
        }
    }
}

Talento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @@version v2.0.0
* @@link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
*
* Adaptated to ASP.NET Core MVC 2.1 by Miguel Veloso
* http://coderepo.blog
-->

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>@ViewData["Title"] - Talento 2.0</title>

    <!-- Icons-->
    <link href="~/lib/@@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
    <link href="~/lib/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <environment include="Development">
        <!-- Template styles -->
        <link href="~/css/style.css" rel="stylesheet">
        <link href="~/vendors/pace-progress/css/pace.css" rel="stylesheet">
        <!-- styles tweaks -->
        <link rel="stylesheet" href="~/css/site.css">

    </environment>

    <environment exclude="Development">
        <!-- Template styles -->
        <link href="~/css/style.min.css" rel="stylesheet" asp-append-version="true">
        <link href="~/vendors/pace-progress/css/pace.min.css" rel="stylesheet" asp-append-version="true">
        <!-- styles tweaks -->
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
    </environment>

    <style>
    </style>
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show bg-gray-100">
  <!-- APP-HEADER-->
  <partial name="_app-header" />
  <!-- /APP-HEADER-->
  <!--<partial name="_CookieConsentPartial" />-->
  <div class="app-body">
    <div class="sidebar">
      <!-- SIDEBAR-NAV -->
      <partial name="_sidebar-nav" />
      <!-- /SIDEBAR-NAV -->
      <button class="sidebar-minimizer brand-minimizer" type="button"></button>
    </div>
    <main class="main">
      <!-- VIEW-BREADCRUMBS -->
      @RenderSection("Breadcrumbs", required: false)
      <!-- /VIEW-BREADCRUMBS -->
      <div class="container-fluid">
        <!-- VIEW-STYLES -->
        @RenderSection("Styles", required: false)
        <!-- /VIEW-STYLES -->
        <div class="animated fadeIn">
          <!-- VIEW-CONTENT -->
          @RenderBody()
          <!-- /VIEW-CONTENT -->
        </div>
        <!-- VIEW-MODALS -->
        @RenderSection("Modals", required: false)
        <!-- /VIEW-MODALS -->
      </div>
    </main>
    <!-- ASIDE-MENU -->
    <partial name="_aside-menu" />
    <!-- /ASIDE-MENU -->
  </div>
  <footer class="app-footer">
    <div class="ml-auto">
      <span>Desarrollado por</span>
      <a style="color:black;" href="http://emme.click/"><b>emme.click</b></a>
    </div>
  </footer>
  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
  </environment>
  <script src="~/lib/popper.js/dist/umd/popper.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="~/lib/pace-progress/pace.min.js"></script>
  <script src="~/lib/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
  <script src="~/lib/@@coreui/coreui/dist/js/coreui.min.js"></script>
  <environment include="Development">
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
  </environment>
  <!-- VIEW-SCRIPTS -->
  @RenderSection("Scripts", required: false)
  <!-- /VIEW-SCRIPTS -->
</body>
</html>

Talento/Views/Shared/_Layout.original.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreUI.Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreUI.Mvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CoreUI.Mvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Talento/Views/Shared/_app-header-nav.cshtml
<ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
        <a asp-area="" asp-controller="Home" asp-action="Index"><i class="far fa-file-alt"></i> Reglas del juego</a>
    </li>
    <li class="nav-item px-3">
        <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-newspaper"></i> Novedades</a>
    </li>
    <li class="nav-item px-3">
        <a href="https://api.whatsapp.com/send?phone=5215562546850"><i class="fab fa-whatsapp"></i> 52-1556-25468-50</a>
    </li>
</ul>

Talento/Views/Shared/_breadcrumb-menu.cshtml
<li class="breadcrumb-menu d-md-down-none">
  <div class="btn-group" role="group" aria-label="Button group">
    <a class="btn" href="#">
      <i class="icon-speech"></i>
    </a>
    <a class="btn" asp-area="" asp-controller="CoreUI" asp-action="Index" asp-route-view="">
      <i class="icon-graph"></i> Dashboard
    </a>
    <a class="btn" href="#">
      <i class="icon-settings"></i> Settings
    </a>
  </div>
</li>

Talento/Views/Shared/_sidebar-nav.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject RoleManager<IdentityRole> RoleManager



@if (User.Identity.IsAuthenticated)
{
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" asp-route-view="Index">
                    <i class="nav-icon icon-home"></i> Inicio

                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index" asp-route-view="index">
                        <i class="nav-icon icon-chart"></i> Dashboard
                        <span class="badge badge-primary">Nuevo</span>
                    </a>
                </li>
            }

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Cursos">
                    <i class="nav-icon icon-folder-alt"></i>Cursos y Certificaciones
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="EbooksYGuias">
                    <i class="nav-icon icon-book-open"></i> Ebooks y Guías
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Eventos">
                    <i class="nav-icon icon-calendar"></i> Eventos
                </a>
            </li>
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-menu"></i> Directorios
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Afiliados">
                            Afiliados
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="DirProv">
                            Proveedores
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="GruposWhats">
                    <i class="nav-icon  fab fa-whatsapp"></i>  Grupos de WhatsApp
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Facebook">
                    <i class="nav-icon icon-social-facebook"></i>Difusión en Facebook
                </a>
            </li>

            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-menu"></i> Empleo
                </a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Empleos-tv">
                            Empleos TV
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Candidato" asp-action="Index" asp-route-view="AddCandidato">
                            Bolsa de Empleos TV
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="ferias-de-empleo">
                            Ferias del Empleo
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="CoreUI" asp-action="Index" asp-route-view="buttons-dropdowns">
                            Base de Candidatos
                        </a>
                    </li>

                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Mensajes-masivos">
                    <i class="nav-icon icon-envelope-letter"></i>Mensajes Masivos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Encuestas">
                    <i class="nav-icon icon-question"></i> Encuestas
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Consultores">
                    <i class="nav-icon icon-people"></i>Consultores
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="CoreUI" asp-action="Index" asp-route-view="icons-simple-line-icons">
                    <i class="nav-icon icon-note"></i> Blog
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Recomiendanos">
                    <i class="nav-icon icon-like"></i>Recomiéndanos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="CoreUI" asp-action="Index" asp-route-view="icons-simple-line-icons">
                    <i class="nav-icon icon-wallet"></i>Productos con tarifas preferentes
                </a>
            </li>

        </ul>
    </nav>
}
else
{
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="" asp-action="" asp-route-view="">
                    Debes de identificarte para poder ver el menú del sistema.
                </a>
            </li>
            <li class="nav-item">                
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Acceder ahora</a>
            </li>
        </ul>
    </nav>
}

Talento/Views/Shared/_user-nav.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using Talento.Clases
@using System.Data

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{

    var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;

    DataTable dt = new DataTable();

    dt = Usuarios.DatosUsuario(user);

}

<li class="nav-item dropdown">
    <a class="nav-item nav-link " b data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        @*<img class="img-avatar" src="~/images/avatars/6.jpg" alt="">*@
        @* @User.Identity.Name *@
        <i class="far fa-user"></i> Hola, @dt.Rows[0][4]   |   @dt.Rows[0][1] <i class="fas fa-sort-down"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
            <strong>Cuenta</strong>
        </div>
        @*
            <a class="dropdown-item" href="#">
              <i class="fa fa-bell-o"></i> Updates
              <span class="badge badge-info">42</span>
            </a>
            <a class="dropdown-item" href="#">
              <i class="fa fa-envelope-o"></i> Messages
              <span class="badge badge-success">42</span>
            </a>
            <a class="dropdown-item" href="#">
              <i class="fa fa-tasks"></i> Tasks
              <span class="badge badge-danger">42</span>
            </a>
            <a class="dropdown-item" href="#">
              <i class="fa fa-comments"></i> Comments
              <span class="badge badge-warning">42</span>
            </a>
            <div class="dropdown-header text-center">
              <strong>Settings</strong>
            </div>
        *@
        <a class="dropdown-item" asp-area="" asp-controller="Talent" asp-action="Index" asp-route-view="Perfil">
            <i class="fa fa-user"></i> Perfil
        </a>
        @*
            <a class="dropdown-item" href="#">
              <i class="fa fa-wrench"></i> Settings
            </a>
            <a class="dropdown-item" href="#">
              <i class="fa fa-usd"></i> Payments
              <span class="badge badge-secondary">42</span>
            </a>
            <a class="dropdown-item" href="#">
              <i class="fa fa-file"></i> Projects
              <span class="badge badge-primary">42</span>
            </a>
            <div class="divider"></div>
            <a class="dropdown-item" href="#">
              <i class="fa fa-shield"></i> Lock Account
            </a>*@

        <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/Index", new {area = ""})" method="post" id="logoutForm">
            <script>
                function logout() {
                    $('#logoutForm').submit();
                }
            </script>
            <a class="dropdown-item" href="javascript: void(0)" onclick="logout()">
                <i class="fa fa-lock"></i> Salir
            </a>
        </form>
    </div>
</li>